### ISSUE TITLE
Your theme seems to break hugoThemeSiteBuilder Repo

### ISSUE THREAD

**Issue by RononDex** [xslingcn/vno-hugo#4]
For more information check the log on my PR:
https://github.com/gohugoio/hugoThemesSiteBuilder/pull/113

```
error: image "images/screenshot.png" not found in "github.com/xslingcn/vno-hugo"
```

Taking a look at your repository, it seems you converted your `/images/screenshot.png` to `/images/screenshot.webp`, causing the build pipeline to fail on all recent PR's

**Comment by xslingcn** [comment]
Yeah I forgot about the requirement from the builder. Should be fixed in [15075b](https://github.com/xslingcn/Vno-Hugo/commit/15075b625774f8c70e2decae8465920a30e0abb9). Sorry for any inconvenience.
