### ISSUE TITLE
Translate Chinese text

### ISSUE THREAD

**Issue by oedbro** [xslingcn/vno-hugo#9]
Some parts of the template is hardcoded in Chinese. It would be great to have a config toggle to have the text be in english instead. An alternative would be to have the full text in the config, so that one can change them on demand instead of changing the theme,

**Comment by xslingcn** [comment]
Hi, thanks for the advice and contributions! I've merged your PRs and added the support of Hugo's multilingual mode in [c111387](https://github.com/xslingcn/Vno-Hugo/commit/c1113877a43805ba5a66c928fc6c2d5dcb16d7d6), this should provide convenience regarding switching languages.
